= Incubation release process
Cédric Champeau <cchampeau@apache.org>
v1.0, June 7, 2015: First version

:teamcity: http://ci.groovy-lang.org
:groovy: http://groovy-lang.org
:bintray: https://bintray.com/[Bintray]
:gradle: http://gradle.org[Gradle]

The goal of this document is to guide the release manager in order to perform a release under the Apache Incubator. This document, reflecting the status of incubation, is work in progress and will be adapted with regards to comments from the community, mentors and IPMC.

== Initiating a release

Releases can be initiated by a committer, as long as:

* an email has been sent to the dev mailing list, where a committer volunteers for a release
* there's a general agreement that a release can be done. There's still no explicit rule telling when a new Groovy version can be released, but the history of the project shows that releases are usually done when a significant amount of bugfixes have been done justifying a release, or that new major features are ready.
* release manager has his personal setup ready. In particular:
** release manager can log into his people.apache.org account using SSH
** release manager has administration privileges on {teamcity}[the CI server]

Releases are launched from the CI server. A release should never be done from a personal computer.

== Preparing a release

Releases are done from the CI server, but since it will involve creating tags, branches and several commits, and that the CI server doesn't have privileges to do it, we cannot work on the Apache Git origin. Instead, it is required that the release manager forks the repository and pushes changes to his personal fork. Given that `GROOVY_2_4_X` is the branch to release, `upstream` references Apache Git, and `origin` the release manager fork on GitHub, preparing for a release usually starts with:

```
git checkout GROOVY_2_4_X
git pull --rebase upstream GROOVY_2_4_X
git push origin GROOVY_GROOVY_2_4_X
```

If you haven't done it already, create a token on https://github.com/settings/tokens[your GitHub profile] so that the CI server can have write access on your fork. Keep the token safe!

== Setup the TeamCity release configuration

Go to the http://ci.groovy-lang.org/admin/editBuild.html?id=buildType:Groovy_BintrayIntegration_ReleasePlan[TeamCity release plan] configuration and open the VCS settings. If the VCS root attached to the configuration is not your GitHub fork, attach your VCS root, or create a new VCS root if you haven't done it already. The VCS root MUST have write access using the token authentication.


== Trigger the release

Go to the http://ci.groovy-lang.org/viewType.html?buildTypeId=Groovy_BintrayIntegration_ReleasePlan&tab=artifactory[Artifactory Release Management tab] and fill the form appropriately:

* _groovyVersion_
** _release version_ must be set to the version number of Groovy you are releasing. For example `2.4.4`.
** _next integration version_ *must* be set to the subsequent version number of Groovy you are releasing and as it will be a development version, *must* end with `-SNAPSHOT`. For example `2.4.5-SNAPSHOT`.
* _groovyBundleVersion_
** _release version_ must be set to the OSGi bundle version number of Groovy you are releasing. For example `2.4.4`.
** _next integration version_ *must* be set to the subsequent OSGi bundle version number of Groovy you are releasing and as it will be a development version, *must* end with `.SNAPSHOT`. For example `2.4.5.SNAPSHOT`.
* _Checkout branch:_ must be set to the branch your are releasing. For example, if you are releasing a 2.4.x version of Groovy, `GROOVY_2_4_X`.
* _Use release branch_ must be checked, and it will automate the creation of a release branch. Use a branch name in the form of `REL_BRANCH_2_4_3`
* _Create VCS tag_ must be checked, and it will automate the creation of a release tag. Use a tag name in the form of `GROOVY_2_4_4`
* _Tag comment_ must be set to something useful describing the release version
* _Repository to stage the release to (Artifactory Pro):_ must be set to `oss-release-local`
* _Staging comment_ should be set with something useful like `release of Groovy 2.4.4`

Hit the release button.

== Upload to Apache servers

At this point, if the release build was successful, artifacts are staging on Bintray. You must log into Bintray and download the distribution artifacts. The URL for
the staging distribution should be in the form of https://bintray.com/groovy/maven/groovy/2.4.4[https://bintray.com/groovy/maven/groovy/2.4.4].

Downloads of the following files are only possible if you use the (groovy-operator,<api key>) credentials. If you don't have them please ask one of the PPMC members:

* apache-groovy-src-_version_-incubating.zip
* apache-groovy-binary-_version_.zip
* apache-groovy-docs-_version_.zip
* apache-groovy-sdk-_version_.zip

as well as the corresponding _asc_ and _md5_ files. There should therefore be a total of _12_ files.

NOTE: at this point it is possible that the MD5 files are missing, in which cases you would have to create them locally before uploading to Apache.
```
for f in `ls *.zip`; do md5sum $f > $f.md5; done
```

Now you are ready to upload to your *personal* Apache space on people.apache.org. You can use `scp`, but in the end the layout must look like this:

```
|-- KEYS
|-- distribution
|   |-- apache-groovy-binary-2.4.4.zip
|   |-- apache-groovy-binary-2.4.4.zip.asc
|   |-- apache-groovy-binary-2.4.4.zip.md5
|   |-- apache-groovy-docs-2.4.4.zip
|   |-- apache-groovy-docs-2.4.4.zip.asc
|   |-- apache-groovy-docs-2.4.4.zip.md5
|   |-- apache-groovy-sdk-2.4.4.zip
|   |-- apache-groovy-sdk-2.4.4.zip.asc
|   `-- apache-groovy-sdk-2.4.4.zip.md5
`-- sources
    |-- apache-groovy-src-2.4.4-incubating.zip
    |-- apache-groovy-src-2.4.4-incubating.zip.asc
    `-- apache-groovy-src-2.4.4-incubating.zip.md5
```

== Push the tag and new HEAD

```
git fetch origin --tags
git push upstream GROOVY_2_4_4
git push upstream GROOVY_2_4_X
```

== Send a [VOTE] thread

You can use the following template to send a VOTE thread on the dev@ list:

```
Dear community,

I am happy to start the VOTE thread for a Groovy xxx-incubating!
This release includes bugfixes for ...

The changelog for this release can be found here: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12318123&version=12331941

Tag: https://git1-us-west.apache.org/repos/asf?p=incubator-groovy.git;a=tag;h=19f70958f39f0cc5c6b4d3e9471fd297400647d2

The artifacts to be voted on are located here: http://people.apache.org/~cchampeau/groovy/

Release artifacts are signed with the following key: http://people.apache.org/~cchampeau/groovy/KEYS

Please vote on releasing this package as Apache Groovy 2.4.4-incubating.

The vote is open for the next 72 hours and passes if a majority of at least three +1 PPMC votes are cast.

[ ] +1 Release Apache Groovy 2.4.4-incubating
[ ]  0 I don't have a strong opinion about this, but I assume it's ok
[ ] -1 Do not release Apache Groovy 2.4.4-incubating because...

Here is my vote:

+1 (binding)
```

